name: chexchonet
channels:
  - sebp
  - pytorch
  - nvidia
  - plotly
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - ignite=0.4.7=py_0
  - pandas=1.4.3=py38h6a678d5_0
  - pillow=9.2.0=py38hace64e9_1
  - pydicom=2.2.2=pyh6c4a22f_0
  - pytorch=1.9.1=py3.8_cuda11.1_cudnn8.0.5_0
  - pyyaml=6.0=py38h7f8727e_1
  - scikit-image=0.19.2=py38h51133e4_0
  - scikit-learn=1.0.1=py38h51133e4_0
  - torchfile=0.1.0=py_0
  - torchinfo=1.7.1=pyhd8ed1ab_0
  - torchmetrics=0.6.0=pyhd8ed1ab_0
  - torchvision=0.10.1=py38_cu111
  - tqdm=4.64.0=py38h06a4308_0
  - visdom=0.1.8.9=0
  - matplotlib-base=3.4.3=py38hf4fb855_1
  - matplotlib-inline=0.1.6=py38h06a4308_0  
  - pip:
      - efficientnet-pytorch==0.7.1
      - numpy==1.22.3
      - opencv-python==4.5.4.60
      - libauc==1.1.8
      - jsonpatch==1.32
